# Generated by Django 3.1.4 on 2021-01-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
