# Generated by Django 3.1.4 on 2021-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20210111_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
