# Generated by Django 3.1.4 on 2021-02-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='service',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='tag',
            new_name='tags',
        ),
    ]
