# Generated by Django 3.1.4 on 2021-02-08 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_auto_20210208_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='servises',
            new_name='Services',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='services',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='tags',
            new_name='tag',
        ),
    ]
