# Generated by Django 3.1.4 on 2021-02-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_auto_20210208_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='category',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='service',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='tag',
            new_name='tags',
        ),
    ]
