# Generated by Django 3.1.4 on 2021-02-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_auto_20210208_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.ManyToManyField(to='contents.Genre'),
        ),
    ]
