# Generated by Django 3.1.4 on 2021-01-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'タグ'},
        ),
    ]
