# Generated by Django 3.1.4 on 2021-02-10 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210111_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
